#! /usr/bin/env bash

IFS=''
LC_ALL='C'

printf "Enter String > "
read -r STRING


### You shouldn't change anything below this line

CFLAGS="-DHELLO=${STRING}"

make -B CFLAGS="-std=gnu98 -Wno-trigraphs ${CFLAGS}" && \
./hello
